import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Nav } from "@/components/navgation";
import { Footer } from "@/components/footer";
import "./globals.css";
import { Amplify } from 'aws-amplify';
import { Auth } from 'aws-amplify/auth';
import amplifyOutputs from "../../amplify_outputs.json";
import { Providers } from "./providers";

amplifyOutputs.data.default_authorization_type = "AWS_IAM";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Department of Physical Education | Christ University BYC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Configure Amplify on client side
  if (typeof window !== 'undefined') {
    Amplify.configure(amplifyOutputs);
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        <Providers>
        {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
